### ISSUE TITLE
Plugin Idea: W3M

### ISSUE THREAD

**Issue by Simon-Laux** [adbenitez/simplebot#2]
To provide text representation of websites.

**Comment by adbenitez** [comment]
do you mean like url previews?

**Comment by Simon-Laux** [comment]
http://w3m.sourceforge.net/

**Comment by Simon-Laux** [comment]
It's a text based webbrowser for the comandline

**Comment by adbenitez** [comment]
also there are tools that convert html to markdown which may be useful when we have markdown support in Delta

**Comment by Simon-Laux** [comment]
> also there are tools that convert html to markdown which may be useful when we have markdown support in Delta
Our markdown support will have no headers. We will only support a subset of markdown.

I made a feature probabsal to propose the markdown reader in dc: https://support.delta.chat/t/open-markdown-files/466
Until then we can implement it in ZHV.
https://github.com/Simon-Laux/ZHV/issues/6

**Comment by adbenitez** [comment]
@Simon-Laux  this is already(time ago sorry the late reply) possible with command /url (simplebot_webgrabber plugin) it returns a text representation of a site, that also happens to be markdown!!! so in a future this could be displayed nicely in Delta Chat
