### ISSUE TITLE
website compression with .htmlzip files

### ISSUE THREAD

**Issue by Simon-Laux** [adbenitez/simplebot#3]
command idea `!webz [url]`:
without url displays a download links/help with a command to ask the bot to send the apk.

https://github.com/Simon-Laux/ZHV
Useful links for implementing:
https://pymotw.com/3/zipfile/index.html#writing-data-from-sources-other-than-files

**Comment by adbenitez** [comment]
thanks!!! yes I think that we should provide zipped versions of commands so users without the apk can still use the bot, then the apk can be optimized to be small enough to send it as attached file with the bot on user request

**Comment by Simon-Laux** [comment]
```py
import zipfile

msg = '<h1>Html file</h1> content text'
with zipfile.ZipFile('name.htmlzip',
                     mode='w',
                     compression=zipfile.ZIP_DEFLATED,
                     ) as zf:
    zf.writestr('index.html', msg)
```
didn't work?

**Comment by adbenitez** [comment]
yes, take a look at https://github.com/adbenitez/simplebot/blob/341ffd551dba7ec3cd7eddb0fd584e4780944cde/simplebot/__init__.py#L89
the issue was that I didn't knew that zhv was expecting the file to be named `index.html`

**Comment by adbenitez** [comment]
it is working now you can test it with the bot: simplebot@riseup.net

**Comment by adbenitez** [comment]
basically if the user is using zhv a prefix command `/zhv` is sent so te bot know you have zhv and sends the reply zipped

**Comment by Simon-Laux** [comment]
cool

**Comment by adbenitez** [comment]
I use the compression even for the bot is own html files, the html is much more smaller now!! :sunglasses:
