### ISSUE TITLE
Make plugins generate html GUI replies to improve UX

### ISSUE THREAD

**Issue by adbenitez** [adbenitez/simplebot#5]
To make it easy for the user to learn and work with the commands, the help plugin could provide an html-based view with the plugins descriptions and buttons to get started using them easily, also other plugins should provide an html GUI if useful.

**Comment by Simon-Laux** [comment]
I would rather say when it's useful rather than when possible.
For a confirm like `!yes` / `!no` you don't need a gui eachtime.
I would say have a !gui command that combinds all guis from all plugins into one html file (.html.zip to save space). That command could provide a dashboard from where you have a gui part for each plugin.

**Comment by adbenitez** [comment]
yes, updated, the GUI should be only when it is useful, sometimes it doesn't improve the UX but it helps to get users started to learn how to use the commands and options

**Comment by Simon-Laux** [comment]
What do you think about the idea to implement a user preferences plugin that gives the option to prefer zipped html / normal html (probably default) / normal text?
The plugins don't need to 100% follow this preference, only where there is a choice and where it's implmented.

**Comment by adbenitez** [comment]
not sure about it, maybe if there are a way to detect with js that users are using your html viewer and then use the zipped commands will be enough

**Comment by Simon-Laux** [comment]
> maybe if there are a way to detect with js that the html is rendering in your html viewer

I don't quite understand how this help us here. You mean to somehow check if ZHV is installed?

**Comment by adbenitez** [comment]
I am talking to the transition from normal html to zipped html, for example: user sends a !help command, this is sent in plain html, js in that html checks the user agent and if it is ZHV, then it sets the mailto links with the zipped versions of the commands other wise it uses the normal commands
(check: https://stackoverflow.com/questions/4825498/how-can-i-find-out-which-browser-a-user-is-using)

**Comment by adbenitez** [comment]
the question is: can you set a custom user agent for your viewer?

**Comment by Simon-Laux** [comment]
I can, but I'll try setting a js var first - that might result in less code.

**Comment by adbenitez** [comment]
so it is possible??? cool, the js var will work also +1

**Comment by adbenitez** [comment]
closed by #10
