### ISSUE TITLE
XKCD plugin

### ISSUE THREAD

**Issue by adbenitez** [adbenitez/simplebot#6]
Send https://xkcd.com images
### Syntaxt:
`!xkcd [number|!r]`

**Comment by Simon-Laux** [comment]
I would make the !r optional/the default - If you don't add it it spits out a random one.
 An option to get the newest one could also be nice.

**Comment by adbenitez** [comment]
The default for "!xkcd" will be to send an html GUI with buttons like "random" and now your "latest" idea which is great +1
