### ISSUE TITLE
Add hooks to simplebot 

### ISSUE THREAD

**Issue by adbenitez** [adbenitez/simplebot#7]
currently plugins are simply kept together in a list and can only handle incoming messages, plugins should register for the events they want to react to, ex. before a message is processed or after a message was processed, etc.

**Comment by adbenitez** [comment]
ex. this will be useful for banning users, or helping users if they sent an unknown command

**Comment by Simon-Laux** [comment]
you probably mean hooks?

**Comment by adbenitez** [comment]
probably ;)

**Comment by adbenitez** [comment]
this is kind of solved in current master which allow to listen to commands and to normal messages, also before and after actions
